set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports o_cs]
set_property IOSTANDARD LVCMOS33 [get_ports i_reset]
set_property IOSTANDARD LVCMOS33 [get_ports o_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports o_spi_mosi]
set_property PACKAGE_PIN E3 [get_ports i_clk]
set_property PACKAGE_PIN J15 [get_ports i_reset]
set_property PACKAGE_PIN D14 [get_ports o_cs]
set_property PACKAGE_PIN F16 [get_ports o_spi_clk]
set_property PACKAGE_PIN G16 [get_ports o_spi_mosi]

#set_property IOSTANDARD LVCMOS33 [get_ports r_clk_10hz]
#set_property PACKAGE_PIN N17 [get_ports r_clk_10hz]